### PR TITLE
Updated thumbnails using @slightlyoff method

### PR DESCRIPTION
**Pull request by hannahbeasley**
I've noticed that thumbnails have not been working on the original version of the script - however [this repo has a solid working solution](https://github.com/slightlyoff/lite-vimeo). This branch just updates the method of fetching the thumbnail!

### CODE REVIEW

**Comment by Jieiku** [comment]
Could you possibly put the compiled version of this on a branch as well? (dist folder) I cannot seem to get a compiled version of this going, but I think maybe it is my version of software, npm, babel, etc...

I am not sure which versions I need installed.

Any help really appreciated!

Here is what I have done so far:

```bash
git clone https://github.com/hannahbeasley/lite-vimeo-embed
cd lite-vimeo-embed
git checkout updated-thumbnail
npm --version
8.5.5
npm run-script build

> lite-vimeo-embed@0.1.0 build
> rollup -c --silent

sh: line 1: rollup: command not found

npm install rollup

npm run-script build

> lite-vimeo-embed@0.1.0 build
> rollup -c --silent

Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
 lite-vimeo-embed.js ⏤  1.51 kB (+1.51 kB)
 lite-vimeo-embed.js ⏤  2.21 kB (+2.21 kB)
```

(YAY it compiled, so I copied the dist file to my server, refresh the page, I can see the vimeo video and click play, but no thumbnail, it is just black)

firefox developer console shows:

`Uncaught ReferenceError: regeneratorRuntime is not defined`

**Comment by obedparla** [comment]
Tested this and can confirm it works. The code in `master` renders some colorful lines but not the correct thumbnail.

**Comment by Jieiku** [comment]
Please post back if you do find a solution and I will do the same. I spent some time on this but had other things I had to focus on, will try again when I find the time.

**Comment by obedparla** [comment]
> Please post back if you do find a solution and I will do the same. I spent some time on this but had other things I had to focus on, will try again when I find the time.

I just used the code in this PR instead of master, and it works. I'm using a script so no fancy build required.

**Comment by Jieiku** [comment]
it worked with the correct thumbnail? If it did then please share the script your using.

**Comment by brandonpeat** [comment]
@hannahbeasley THANK YOU for this fix! Trying to fix the conflicts between the original and the slightlyoff versions was breaking my brain. Your commit changes gave me exactly what I needed to tweak our own version of the code. 🙌

**Comment by Jieiku** [comment]
> @hannahbeasley THANK YOU for this fix! Trying to fix the conflicts between the original and the slightlyoff versions was breaking my brain. Your commit changes gave me exactly what I needed to tweak our own version of the code. raised_hands

@brandonpeat Do you have a fork I could look at? maybe with the compiled script? Would really appreciate it if you do!

EDIT: actually by inspecting the insight network graph I believe I have found a working one here: https://github.com/zaengle/lite-vimeo-embed

**Review by Jieiku — APPROVED** [review]

**Comment by luwes** [comment]
Thanks for the contributions and sorry I wasn't responsive on this.
I updated the custom element with a working solution.

**Pull request closed without merging**
